name: Fatal Fitness
favicon: null
layout_spectrum: 0.34863
typography_spectrum: 0.9077403638511896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4080bf'
    - '#000000'
    - '#008080'
    - '#cc8855'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
